#  포트 랜덤 -> 수정 필
server:
  port: 8081

spring:
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
  application:
    name: recommend-server

  data:
    mongodb:
      uri: mongodb://music:note@localhost:27017/typedb?authSource=admin

  datasource:
#    url: jdbc:mysql://mysql-db/member?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    url: jdbc:mysql://localhost:3306/member?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: music
    password: note
    driver-class-name: com.mysql.cj.jdbc.Driver

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
#      defaultZone: http://eureka-server:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

jwt:
  secret: music-note-jwt-key
