server:
  port: 8000

spring:
  application:
    name: gateway
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]': # 모든 경로에 대해 CORS 허용
            allowedOrigins:
              - "http://localhost:3000"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
      routes:
        - id: main-route
          uri: lb://main-server
          predicates:
            - Path=/api/v1/main/**

        - id: auth-route
          uri: lb://auth-server
          predicates:
            - Path=/api/v1/auth/**
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

