server:
  port: 8761

#마이크로 서비스 고유한 ID -> 어플리케이션 네임
spring:
  application:
    name: gateway-server

#유레카 클라이언트 설정. -> 유레카 라이브러리가 포함된 채 스프링이 기동되면 기본적으로 유레카 클라이언트 역할로서 어딘가에 등록하는 역할
#설정하지 않으면 default true로 설정된다. 기본적으로 현재 작업하는 것은 클라이언트 정보를 전화번호부에 등록한다.
#즉, 자신의 정보를 등록하지 않아도 돈다. 서버로서 기동만 하면 된다.
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false