#  포트 랜덤 -> 수정 필
server:
  port: 0

spring:
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
  application:
    name: auth-server

  datasource:
    url: jdbc:mysql://mysql-db/member?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: music
    password: note
    driver-class-name: com.mysql.cj.jdbc.Driver


spotify:
  client-id: 286e4cbfc6b94a13ae7cb27f0d1f066c
  client-secret: ecec3a3c3e1144f4bc3f055c06c2928e
  user-info-uri: https://api.spotify.com/v1/me

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
#      defaultZone: http://localhost:8761/eureka
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

jwt:
  secret: music-note-jwt-key
  expiration: 86400000  # JWT 만료 시간 (예: 1시간)
  refreshExpiration: 864000000
